# Generated by Django 6.1.1 on 2026-09-23 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
